/*
 * Simple Inventory API
 *
 * This is API for cloud-based microservice
 *
 * API version: 1.0.0
 * Contact: newmail@mail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"encoding/json"
	"net/http"
)

func DeleteAll(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	type ViewData struct {
		Status string
	}
	data := ViewData{
		Status: "OK",
	}
	StatusJson, err := json.Marshal(data)
	if err != nil {
		panic(err)
	}
	w.Write(StatusJson)
}

func GetAllInfo(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	type ViewData struct {
		Status string
	}
	data := ViewData{
		Status: "OK",
	}
	StatusJson, err := json.Marshal(data)
	if err != nil {
		panic(err)
	}
	w.Write(StatusJson)
}
