/*
 * Simple Inventory API
 *
 * This is API for cloud-based microservice
 *
 * API version: 1.0.0
 * Contact: newmail@mail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"encoding/json"
	"net/http"
)

func DeleteAll(w http.ResponseWriter, r *http.Request) {
	deleteAll(LOGS)
	deleteAll(METRICS)
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func GetAllInfo(w http.ResponseWriter, r *http.Request) {
	type Response struct {
		Logs string
		Metrics string
	}
	responseRaw := Response{
		Logs: getAll(LOGS),
		Metrics: getAll(METRICS),
	}

	response, err := json.Marshal(responseRaw)
	if err != nil {
		panic(err)
	}
	w.Write(response)


	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	//w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	//w.WriteHeader(http.StatusOK)
}
