/*
 * Simple Inventory API
 *
 * This is API for cloud-based microservice
 *
 * API version: 1.0.0
 * Contact: newmail@mail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"github.com/gorilla/mux"
	"html/template"
	"net/http"
	"strings"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	type ViewData struct {
		DelAll      string
		GetAll      string
		GetLogsById string
	}
	data := ViewData{
		DelAll:      "/all DELETE",
		GetAll:      "/all GET",
		GetLogsById: "/logs/id GET",
	}
	tmpl, _ := template.ParseFiles("../templates/main.html")
	tmpl.Execute(w, data)
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"DeleteAll",
		strings.ToUpper("Delete"),
		"/all",
		DeleteAll,
	},

	Route{
		"GetAllInfo",
		strings.ToUpper("Get"),
		"/all",
		GetAllInfo,
	},

	Route{
		"DeleteAllLogs",
		strings.ToUpper("Delete"),
		"/logs/deleteAll",
		DeleteAllLogs,
	},

	Route{
		"DeleteLogsById",
		strings.ToUpper("Delete"),
		"/logs",
		DeleteLogsById,
	},

	Route{
		"GetLogsById",
		strings.ToUpper("Get"),
		"/logs",
		GetLogsById,
	},

	Route{
		"PostLogs",
		strings.ToUpper("Post"),
		"/logs",
		PostLogs,
	},

	Route{
		"DeleteAllMetrics",
		strings.ToUpper("Delete"),
		"/metrics/deleteAll",
		DeleteAllMetrics,
	},

	Route{
		"DeleteMetricById",
		strings.ToUpper("Delete"),
		"/metrics",
		DeleteMetricById,
	},

	Route{
		"GetMetricById",
		strings.ToUpper("Get"),
		"/metrics",
		GetMetricById,
	},

	Route{
		"PostMetric",
		strings.ToUpper("Post"),
		"/metrics",
		PostMetric,
	},
}
